
extend: image.yaml

version: &version 1.0.0-rc

development:
    version: *version
    pg:
        host: ''
        port: ''
    redis:
        host: ''
        port: ''

production:
    version: *version
    pg:
        host: ''
        port: ''
    redis:
        host: ''
        port: ''
